#!/bin/sh
#
# Autorun script for CentOS
# Copyright (c) 1999-2002 Red Hat, Inc.

dir=$(echo $0 |sed 's/autorun//')
cd $dir
tree=$(pwd)

# Change directories so we can unmount the CD-ROM Drive
cd /
exec /usr/bin/redhat-cdinstall-helper $tree
